version: '3.8'
services:
  es:
    image: rasenshuriken/elasticsearch_no_security:8.6.1
    ports: 
      - 9200:9200


  api:
    image: praveenvenkat06/test_spring_docker:latest
    ports: 
      - 8080:8080

  
    
      